Main_project_school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import entry_page_view

urlpatterns = [
    path('', entry_page_view, name='entry_page'),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('manager-school/', include('manager_school.urls')),
    path('admin_school/',include('admin_school.urls')),
    path('director-school/', include('director_school.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .views import *


app_name = 'student'

urlpatterns = [
    path("logout/",logout_request,name='logout'),
    path("login/",login_user,name="login"),
    path('change_data/', Change_user_info, name='change_data'),
    path('', main_page_view, name='main_page_view'),
    path('account/', account, name="account"),
    path('calendar/', calendar, name='calendar'),
    path('process/', process, name='process'),
    path('my_group/', group_view, name="group_view"),
    path('group_profile/<int:user_id>/', group_profile, name='group_profile'),
    path('teachers/', teacher_view, name='teacher'),
    path('teacher_profile/<int:teacher_id>/', teacher_profile, name='teacher_profile'),
    path('homework/', homework_view, name="homework"),
    path('exact_hw/<int:homework_id>/', exact_homework, name='exact_hw'),
    path('materials/', materials_view, name="materials_view"),
    path('material_themes/', material_themes, name="material_themes"),
    path('material_detail/<int:class_id>/', material_detail, name="material_detail"),
    path('study_liter/', liter_view, name='study_literature'),
    path('video_materials/', video_materials, name="video_materials"),
    path('video_themes/', video_themes, name='video_themes'),
    path('video_detail/<int:class_id>/', video_detail, name='video_detail'),
    path('class/<int:class_id>/detail/', class_view, name="class_view"),
    path('contact_admin/', contact_admin, name="contact_admin"),
    path('itnews/', itnews, name="itnews"),
    path('itnews/<int:news_id>/detail', news_detail, name="news_detail"),
    path('services/', services, name="services"),
    path('payment_stages/', payment, name="payment"),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('api/v1/classes-list/', api_classes_list),
]

manager_school/models.py
import datetime

from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils import timezone
from .utilities import slugify
from time import time
# Create your models here.


def gen_slug(s):
    new_slug = slugify(s)
    return new_slug + '-' + str(int(time()))


class AdvUser(AbstractUser): # Студенты
    surname = models.CharField(max_length=30, db_index=True, verbose_name="Отчество", blank=True)
    img_user = models.ImageField('Аватар', upload_to='images/user/', blank=True)
    phone = models.CharField(max_length=30, verbose_name="Номер телефона", blank=True)

    def get_academic_performance(self, group_id=''):
        if self.groups.filter(name="Student").exists():
            academic_performance = 0
            if group_id == '':
                attendances = self.attendances.all()
                attendances_true = self.attendances.filter(attendance='Присутствует')
                homework = self.homework_st.filter(status='Проверено')
            else:
                attendances = self.attendances.filter(classes__groups__id=group_id)
                attendances_true = self.attendances.filter(attendance='Присутствует', classes__groups__id=group_id)
                homework = self.homework_st.filter(status='Проверено', class_field__groups__id=group_id)
            if attendances_true:
                for attendance in attendances_true:
                    academic_performance += attendance.rating
            if homework:
                for hw in homework:
                    academic_performance += hw.rating
            try:
                return int(academic_performance / (len(attendances)+len(homework))) * 10
            except ZeroDivisionError:
                return 0
        return 0
# !!! ВЕРНУТЬ ФЛОАТ В ВЫВОД ЗНАЧЕНИЯ (ПОМЕНЯТЬ ДВОЙНОЙ СЛЭШ НА ОДИНАРНЫЙ)
    def get_attendance(self, group_id=''):
        if self.groups.filter(name="Student").exists():
            current_day = datetime.date.today()
            if group_id == '':
                attendances = self.attendances.all()
                classes = ClassModel.objects.filter(groups__students__id=self.id, date__lt=current_day)
            else:
                attendances = self.attendances.filter(classes__groups__id=group_id)
                classes = ClassModel.objects.filter(
                    groups__students__id=self.id, groups__id=group_id, date__gt=current_day)
            try:
                attendance = len(attendances.filter(attendance='Присутствует')) / len(classes) * 100
            except ZeroDivisionError:
                attendance = 0
            return int(attendance)# Вот тут инт убрать
        return 0

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.surname}"

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class UserManagement(models.Model):
    student = models.OneToOneField(AdvUser, on_delete=models.SET_NULL, null=True, verbose_name="Студент", related_name="management")
    manager = models.ForeignKey(AdvUser, on_delete=models.SET_NULL, null=True, verbose_name="Менеджер", related_name="user_management")

    class Meta:
        verbose_name = 'Привязка к менеджеру'
        verbose_name_plural = 'Привязки к менеджерам'


class CourseUser(models.Model):  # Курс
    title = models.CharField(max_length=150, db_index=True, verbose_name='Название', blank=True)
    description = models.TextField('Описание', blank=True)
    price = models.FloatField(verbose_name='Цена', default =0)
    start_date = models.DateField(verbose_name='Начало занятий', null=True)
    finish_date = models.DateField(verbose_name='Конец занятий', null=True)
    img = models.ImageField(upload_to='images/courses/', verbose_name='Логотип курса')
    amount = models.CharField(max_length=50, db_index=True, verbose_name='Количество занятий')
    slug = models.SlugField(max_length=100, db_index=True, default=None)
    is_online = models.BooleanField(default=False, verbose_name="Онлайн?")

    def __str__(self):
        return f"{self.title}"

    def get_obj(self):
        return self.id, self.title

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'


class GroupModel(models.Model):     # Группа
    students = models.ManyToManyField(AdvUser)
    teacher = models.ForeignKey(AdvUser, verbose_name='Учитель', on_delete=models.PROTECT, related_name='groups_teacher', default=None, null=True)
    manager = models.ForeignKey(AdvUser, verbose_name='Куратор', on_delete=models.PROTECT, related_name='groups_manager', default=None, null=True)
    course = models.ForeignKey(CourseUser, verbose_name='Курс', on_delete=models.CASCADE, related_name='groups', default=None, null=True)
    title = models.CharField('Название', max_length=100, blank=True)
    slug = models.SlugField(max_length=100, db_index=True, default=None, null=True)


    def course_postponation(self, number):
        classes = self.classes.all()
        for cls in classes:
            cls.date += datetime.timedelta(weeks=int(number))
            cls.save()


    def get_academic_performance(self):
        attendances = Attendance.objects.filter(classes__groups__id=self.id)
        attendances_count = len(attendances)
        performance = 0
        if attendances:
            for attendance in attendances:
                if attendance.rating:
                    performance += attendance.rating
                else:
                    attendances_count -= 1
            return round(performance / attendances_count, 2)
        else:
             return 0.0

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class ClassModel(models.Model):  # Занятие
    groups = models.ForeignKey(GroupModel, verbose_name='Группа', on_delete=models.CASCADE, related_name='classes',
                               default=None, null=True)
    classroom = models.ForeignKey('Classroom', on_delete=models.CASCADE, default=None, related_name='classroom',
                                  null=True)
    date = models.DateField(null=True, verbose_name='Дата проведения занятия')
    start_time = models.TimeField(null=True, verbose_name='Время начала занятия')
    end_time = models.TimeField(null=True, verbose_name='Время окончания занятия')
    time_interval = models.ForeignKey('RoomTimeInterval', on_delete=models.PROTECT, default=None, null=True,
                                      related_name='classtime')
    theme = models.CharField(max_length=250, verbose_name='Тема', blank=True)
    file = models.FileField(upload_to='file/video_course/', verbose_name='Файл с видео', blank=True)
    slug = models.SlugField(max_length=100, db_index=True, default=None, blank=True)
    position = models.IntegerField(default=1, null=True, verbose_name="Номер занятия")
    room_link = models.URLField(null=True, blank=True, verbose_name="Ссылка на комнату занятия")
    message = models.TextField(verbose_name='Сообщение', blank=True)

    def __str__(self):
        return self.theme

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.theme)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['groups', 'date']
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'


class Attendance(models.Model): #Посещение

    classes = models.ForeignKey(ClassModel, on_delete=models.CASCADE, related_name='attendances')
    CHOICES = (
        ('Присутствует', 'Присутствует'),
        ('Отсутствует', 'Отсутствует'),
        ('Отсутствует по уважительной причине', 'Отсутствует по уважительной причине'),
        )
    classes =models.ForeignKey(ClassModel, on_delete=models.CASCADE, related_name='attendances')
    students = models.ForeignKey(AdvUser, on_delete=models.CASCADE, related_name="attendances")
    rating = models.IntegerField('Оценка', null=True, blank=True)
    attendance = models.CharField(max_length=300, choices=CHOICES, default='Отсутствует')

    class Meta:
        ordering = ['students', 'attendance', 'rating',]
        verbose_name = 'Посещение'
        verbose_name_plural = 'Посещения'


class Notification(models.Model): #уведомление для группы
    sender = models.ForeignKey(ClassModel, on_delete=models.CASCADE, null=True, related_name='sender_notification',
                               verbose_name='Отправитель')
    recipient = models.ForeignKey(GroupModel, on_delete=models.CASCADE, verbose_name='Получатель')
    message = models.TextField(verbose_name='Сообщение')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = 'Уведомление о изменении '
        verbose_name_plural = 'Уведомления о изменениях'


class PersonalNotification(models.Model): #персональные уведомления
    recipient = models.ForeignKey(AdvUser, verbose_name='Получатель', on_delete=models.CASCADE)
    message = models.TextField(max_length=512, verbose_name='Текст уведомления')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Время получения')

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = 'Персональное уведомление'
        verbose_name_plural = 'Персональные уведомления'


class Classroom(models.Model): #Аудитория
    title = models.CharField('Аудитория', max_length=50)
    max_places_count = models.IntegerField(null=True, blank=True, verbose_name="Количество мест в аудитории")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Аудитория'
        verbose_name_plural = 'Аудитории'

student/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from manager_school.models import AdvUser
from django.contrib.auth.models import User


class UserEditForm(forms.ModelForm):
    class Meta:
        model = AdvUser
        fields = ('email', 'phone', 'img_user',)


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'placeholder': 'Логин *'},))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'placeholder': 'Пароль *'}),)

templates/student/card_of_another_student.html
{% extends 'student/base_student.html' %}
{% load static %}
    <title>Карточка студента</title>
{% block style %}
    <link rel="stylesheet" href="{% static 'css/main-header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/card_of_another_student.css' %}">
{% endblock %}
{% block header %}
      <div class="main-header__page-information-change-specialty">
        <p class="main-header__page-information">Карточка студента</p>
      </div>
{% endblock %}
{% block content %}
    <main>
      <div class="main__another-student-card">
        <div class="main__another-student-card-info">
            <div class="main__another-student-card-box">
                <div class="main__another-student-card-foto">
                    {% if student.img_user %}
                        <img src="{{ student.img_user.url }}" alt="личное фото" class="main__another-student-card-img">
                    {% else %}
                        <img src="{% static 'images/no-photo.png' %}" style="object-fit: cover;" alt="личное фото" class="main__another-student-card-img"/>
                    {% endif %}
                    <p class="main__personal-another-student-message">
                        <a href="{% url 'student:create_dialog' user_id=student.id %}" class="main__personal-another-student-link">
                            Отправить сообщение
                        </a>
                    </p>
                </div>
                <div class="main__another-student-card-data">
                    <p class="main__another-student-card-data-text">
                        {{ student.first_name }}
                    </p>
                    <p class="main__another-student-card-data-text">
                        {{ student.surname }}
                    </p>
                    <p class="main__another-student-card-data-text main__another-student-card-data-text_weigth">
                        {{ student.last_name }}
                    </p>
                    <p class="main__another-student-card-data-text_size">
                        <span class="main__another-student-card_weight">
                            E-mail
                        </span>
                        {{ student.email }}
                    </p>
                    <p class="main__another-student-card-data-text_size">
                        <span class="main__another-student-card_weight">
                            Тел.:
                        </span>
                        {{ student.phone }}
                    </p>
                </div>
            </div>
            <!-- <div class="main__personal-student-card-perfomance">
                <div class="main__personal-student-card-perfomance-visit">
                    <p class="main__personal-student-card-perfomance-text">
                        Посещение
                    </p>
                    <div class="circle">
                        80%
                    </div>
                    <p class="main__personal-student-card-perfomance-text">
                        80%
                    </p>
                </div>
                <div class="main__personal-student-card-perfomance-academic">
                    <p class="main__personal-student-card-perfomance-text">
                        Успеваемость
                    </p>
                    <div class="circle">
                        20%
                    </div>
                    <p class="main__personal-student-card-perfomance-text">
                        80%
                    </p>
              </div>
            </div>
        </div> -->
    </div>
    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/main-header.js' %}"></script>
{% endblock %}

templates/student/group.html
{% extends 'student/base_student.html' %}
{% load static %}
{% block title %}
    <title>Группа</title>
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/group.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main-group.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main-header.css' %}"/>
{% endblock %}
{% block header %}
    <div class="main-header__page-information-change-specialty">
        <p class="main-header__page-information">Группа</p>
        <div class="main-header__change-speciality">
            <div class="main-header__box-for-change-speciality">
                <p class="main-header__button-change-speciality">{{ group.title }}</p>
                <div class="main-header__list-speciality no-active">
                    <form action="" method="get" class="main-header__form-change-course">
                        <input type="text" name="group" hidden class="main-header__change-course"/>
                        {% for group in groups %}
                            <p class="main-header__wrapp-for-speciality-link mb-0" data-value="{{ group.id }}">
                                {{ group.title }}
                            </p>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <main class="group">
        <div class="group__container">
            <div class="group__list-students">
                <p class="group__name-list">Список учеников</p>
                {% for student in students %}
                    <div class="group__student-box">
                        <p class="group__box-for-foto-student">
                            {% if student.img_user %}
                                <img src="{{ student.img_user.url }}" alt="фото студента" class="group__student-foto"/>
                            {% else %}
                                <img src="{% static 'images/no-photo.png' %}" style="object-fit: cover;"
                                     alt="фото студента" class="group__student-foto"/>
                            {% endif %}
                            <span class="group__check-online"></span>
                        </p>
                        {% if student.id == request.user.id %}
                            <a href="{% url 'student:account' %}">
                        {% else %}
                            <a href="{% url 'student:group_profile' user_id=student.id %}">
                        {% endif %}
                        <p class="group__student-last-name ">{{ student.last_name }}</p>
                        <p class="group__student-first-name">{{ student.first_name }}</p>
                        <p class="group__student-patronymic">{{ student.surname }}</p>
                        </a>
                        <a href="{% url 'student:create_dialog' user_id=student.id %}" class="group__sent-message-link">
                            <p class="group__box-for-link">Отправить сообщение</p>
                        </a>
                    </div>
                {% endfor %}
                <!--          <div class="group__student-box">-->
                <!--            <p class="group__box-for-foto-student">-->
                <!--              <img src="{% static 'img/foto_student.jpg' %}" alt="фото студента" class="group__student-foto" />-->
                <!--              <span class="group__check-online"></span>-->
                <!--            </p>-->
                <!--            <p class="group__student-last-name">Фамилия</p>-->
                <!--            <p class="group__student-first-name">Имя</p>-->
                <!--            <p class="group__student-patronymic">Отчество</p>-->
                <!--            <a href="#" class="group__sent-message-link">-->
                <!--              <p class="group__box-for-link">Отправить сообщение</p>-->
                <!--            </a>-->
                <!--          </div>-->


                <!--          <div class="group__student-box">-->
                <!--            <p class="group__box-for-foto-student">-->
                <!--              <img src="{% static 'img/foto_student.jpg' %}" alt="фото студента" class="group__student-foto" />-->
                <!--              <span class="group__check-online"></span>-->
                <!--            </p>-->
                <!--            <p class="group__student-last-name">Фамилия</p>-->
                <!--            <p class="group__student-first-name">Имя</p>-->
                <!--            <p class="group__student-patronymic">Отчество</p>-->
                <!--            <a href="#" class="group__sent-message-link">-->
                <!--              <p class="group__box-for-link">Отправить сообщение</p>-->
                <!--            </a>-->
                <!--          </div>-->


                <!--          <div class="group__student-box">-->
                <!--            <p class="group__box-for-foto-student">-->
                <!--              <img src="{% static 'img/foto_student.jpg' %}" alt="фото студента" class="group__student-foto" />-->
                <!--              <span class="group__check-online"></span>-->
                <!--            </p>-->
                <!--            <p class="group__student-last-name">Фамилия</p>-->
                <!--            <p class="group__student-first-name">Имя</p>-->
                <!--            <p class="group__student-patronymic">Отчество</p>-->
                <!--            <a href="#" class="group__sent-message-link">-->
                <!--              <p class="group__box-for-link">Отправить сообщение</p>-->
                <!--            </a>-->
                <!--          </div>-->


                <!--          <div class="group__student-box">-->
                <!--            <p class="group__box-for-foto-student">-->
                <!--              <img src="{% static 'img/foto_student.jpg' %}" alt="фото студента" class="group__student-foto" />-->
                <!--              <span class="group__check-online"></span>-->
                <!--            </p>-->
                <!--            <p class="group__student-last-name">Фамилия</p>-->
                <!--            <p class="group__student-first-name">Имя</p>-->
                <!--            <p class="group__student-patronymic">Отчество</p>-->
                <!--            <a href="#" class="group__sent-message-link">-->
                <!--              <p class="group__box-for-link">Отправить сообщение</p>-->
                <!--            </a>-->
                <!--          </div>-->


                <!--          <div class="group__student-box">-->
                <!--            <p class="group__box-for-foto-student">-->
                <!--              <img src="{% static 'img/foto_student.jpg' %}" alt="фото студента" class="group__student-foto" />-->
                <!--              <span class="group__check-online"></span>-->
                <!--            </p>-->
                <!--            <p class="group__student-last-name">Фамилия</p>-->
                <!--            <p class="group__student-first-name">Имя</p>-->
                <!--            <p class="group__student-patronymic">Отчество</p>-->
                <!--            <a href="#" class="group__sent-message-link">-->
                <!--              <p class="group__box-for-link">Отправить сообщение</p>-->
                <!--            </a>-->
                <!--          </div>       -->
            </div>
            <div class="group__box-for-teacher">
                <p class="group__teacher">Преподаватель</p>
                {% if group.teacher.img_user %}
                    <img src="{{ group.teacher.img_user.url }}" alt="фото преподавателя" class="group__teacher-foto">
                {% else %}
                    <img src="{% static 'images/no-photo.png' %}" style="object-fit: cover;" alt="фото преподавателя"
                         class="group__teacher-foto"/>
                {% endif %}
                <p class="group__first-name-and-patronymic">{{ group.teacher.first_name }} {{ group.teacher.surname }}</p>
                <p class="group__last-name">{{ group.teacher.last_name }}</p>
            </div>
        </div>
    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/group.js' %}"></script>
    <script src="{% static 'js/main-header.js' %}"></script>
{% endblock %}

templates/student/itnews.html
{% extends 'student/base_student.html' %}
{% load static %}
{% block title %}
    <title>Новости школы</title>
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/itnews.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/materials_on_topics.css' %}"/>
{% endblock %}
{% block header %}
    <div class="main-header__page-information-change-specialty">
        <p class="main-header__page-information">Новости школы</p>
        <div class="main-header__change-speciality">
            <div class="main-header__box-for-change-speciality">
                {% if current_rubrick %}
                    <p class="main-header__button-change-speciality">{{ current_rubrick.title }}</p>
                {% else %}
                    <p class="main-header__button-change-speciality">Все новости</p>
                {% endif %}
                <div class="main-header__list-speciality no-active">
                    <form action="" method="get" class="main-header__form-change-course">
                        <input type="text" name="rubrick" hidden class="main-header__change-course"/>
                        <p class="main-header__wrapp-for-speciality-link mb-0" data-value="">
                            Все новости
                        </p>
                        {% for rubrick in rubricks %}
                            <p class="main-header__wrapp-for-speciality-link mb-0" data-value="{{ rubrick.id }}">
                                {{ rubrick.title }}
                            </p>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <main class="main">
        <div class="main__it-news">
            {% for news in news %}
                <div class="main__it-news-box">
                    {% if news.img %}
                    <img src="{{ news.img.url }}" style="object-fit: cover;" alt="новость" class="main__it-news-img">
                    {% endif %}
                    <p class="main__it-news-text">
                        <a href="{% url 'student:news_detail' news_id=news.id %}" class="main__it-news-link">
                            {{ news.title }}
                        </a>
                    </p>
                </div>
            {% endfor %}
    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/itnews.js' %}"></script>
    <script src="{% static 'js/main-header.js' %}"></script>
{% endblock %}

templates/student/login.html
{% extends "base_login.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}
Вход
{%endblock%}

{% block content %}

{% if user.is_authenticated%}
<p>Вы уже вылонили вход</p>
<a href="{% url 'student:main_page_student' %}">Главная</a>
<li><a href="{%url 'student:logout'%}">выход</a></li>

{%else%}
<form method="post">
    {% csrf_token %}
      {{ form|crispy }}
      <input type="hidden" name="next" value="{{next}}">
      <input type="submit" value="войти">

</form>
{%endif%}
{% endblock %}

templates/student/studying_proccess.html
{% extends 'student/base_student.html' %}
{% load static %}
{% block title %}
<title>Учебный процесс</title>
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/studying_proccess.css' %}"/>
<link rel="stylesheet" href="{% static 'css/studing-process.css' %}">
{% endblock %}
{% block header %}
<div class="main-header__page-information-change-specialty">
    <p class="main-header__page-information">Учебный процесс</p>
</div>
{% endblock %}
{% block content %}
<main>
    <div class="main__student-process">
        <a href="{% url 'student:homework' %}" class="main__student-process-link">
        <div class="main__student-process-box">
            <img src="{% static 'img/home_work.svg' %}" alt="домашнее задание" class="main__student-process-img"/>
            <p class="main__student-process-text">
                    Домашнее задание
            </p>
        </div>
        </a>
        <a href="{% url 'student:materials_view' %}" class="main__student-process-link">
        <div class="main__student-process-box">
            <img src="{% static 'img/educational_materials.svg' %}" alt="Учебные материалы" class="main__student-process-img"/>
            <p class="main__student-process-text">
                    Учебные материалы
            </p>
        </div>
        </a>
        {% for x in request.user.groupmodel_set.all %}
        <a href="{% url 'student:group_view'  %}" class="main__student-process-link">
        {% endfor %}
        <div class="main__student-process-box">
            <img src="{% static 'img/group1.svg' %}" alt="Группа" class="main__student-process-img"/>
            <p class="main__student-process-text">
                    Группа
            </p>
        </div>
        </a>
        <a href="{% url 'student:teacher' %}" class="main__student-process-link">
        <div class="main__student-process-box">
            <img src="{% static 'img/teacher.svg' %}" alt="Преподаватели" class="main__student-process-img"/>
            <p class="main__student-process-text">
                    Преподаватели
            </p>
        </div>
        </a>
    </div>
</main>
{% endblock %}
{% block script %}
<script src="{% static 'js/studying_proccess.js' %}"></script>
{% endblock %}