Main_project_school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import entry_page_view

urlpatterns = [
    path('', entry_page_view, name='entry_page'),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('manager-school/', include('manager_school.urls')),
    path('admin_school/',include('admin_school.urls')),
    path('director-school/', include('director_school.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_school/urls.py
from django.urls import path

from .views import *

app_name = 'manager_school'

urlpatterns = [
    path("logout/", logout_request, name='logout'),
    path("login/", login_user, name="login"),
    path('registration_user/<int:lead_id>/', register_user, name='registration_page'),
    path('registration_user/unique/', register_user_unique, name='registration_user'),
    path('profile/', get_manager_profile, name='get_manager_profile'),
    path('profile/change-user-info/', change_user_info, name='change_user_info'),
    path('', main_page_view, name='main_page'),
    path('groups/', get_groups, name='get_groups'),
    path('group/create/', add_group, name='add_group'),
    path('group/<str:slug>/add-classes', create_group_classes_page, name='create_group_classes'),
    path('group/<str:slug>/detail/', get_group_detail, name='get_group_detail'),
    path('group/<str:slug>/settings/', group_settings, name='group_settings'),
    path('group/<str:slug>/journal/', get_group_journal, name='get_group_journal'),
    path('group/<int:group_id>/student/<int:student_id>/card/', get_student_card, name='get_student_card'),
    path('classes/', get_classes, name='get_classes'),
    path('class/<int:class_id>/detail/', get_class_detail, name='get_class_detail'),
    path('teachers/', get_teachers, name='get_teachers'),
    path('teacher/<int:teacher_id>', get_teacher_card, name='get_teacher_card'),
    path('leads/', get_leads, name='get_leads'),
    path('lead-create/', add_lead, name='add_lead'),
    path('lead/<int:lead_id>/history/', lead_history, name='lead_history'),
    path('lead/<int:lead_id>/add/conversation/', add_req_conversation, name='add_req_conversation'),
    path('lead/<int:lead_id>/confirm/', confirm_lead, name='confirm_lead'),
    path('contracts/', get_contracts, name='get_contracts'),
    path('contracts/create/choice/<int:lead_id>/', get_choice, name='get_choice'),
    path('contracts/create/<int:lead_id>/<int:student_id>/', create_contract_page, name='create_contract_page'),
    path('contract/<int:contract_id>/payment/<int:payment_id>/add-stage/', add_payment_stage, name='add_payment_stage'),
    path('contract/<int:contract_id>/', get_contract_detail, name='get_contract_detail'),
    path('payment-stage/<int:payment_stage_id>/', confirm_payment_stage, name='confirm_payment_stage'),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/create-group-chat/<str:slug>/', start_group_chat, name='create_group_chat'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('planning/', get_planning_rooms_page, name='planning_rooms_page'),
    path('planning/class/<int:class_id>/update/', update_class_date_and_time, name='update_class_date_and_time'),
    path('news/', get_news_list, name='get_news_list'),
    path('api/v1/classes-list/', api_classes_list),
    path('api/v1/leads-list/', api_leads_list),
    path('api/v1/news/', news_list),
    path('api/v1/online-courses-list/', api_online_course_list),
    path('api/v1/offline-courses-list/', api_offline_course_list),
    path('api/v1/course-detail/<int:course_id>', api_course_detail),

]

student/urls.py
from django.urls import path
from .views import *


app_name = 'student'

urlpatterns = [
    path("logout/",logout_request,name='logout'),
    path("login/",login_user,name="login"),
    path('change_data/', Change_user_info, name='change_data'),
    path('', main_page_view, name='main_page_view'),
    path('account/', account, name="account"),
    path('calendar/', calendar, name='calendar'),
    path('process/', process, name='process'),
    path('my_group/', group_view, name="group_view"),
    path('group_profile/<int:user_id>/', group_profile, name='group_profile'),
    path('teachers/', teacher_view, name='teacher'),
    path('teacher_profile/<int:teacher_id>/', teacher_profile, name='teacher_profile'),
    path('homework/', homework_view, name="homework"),
    path('exact_hw/<int:homework_id>/', exact_homework, name='exact_hw'),
    path('materials/', materials_view, name="materials_view"),
    path('material_themes/', material_themes, name="material_themes"),
    path('material_detail/<int:class_id>/', material_detail, name="material_detail"),
    path('study_liter/', liter_view, name='study_literature'),
    path('video_materials/', video_materials, name="video_materials"),
    path('video_themes/', video_themes, name='video_themes'),
    path('video_detail/<int:class_id>/', video_detail, name='video_detail'),
    path('class/<int:class_id>/detail/', class_view, name="class_view"),
    path('contact_admin/', contact_admin, name="contact_admin"),
    path('itnews/', itnews, name="itnews"),
    path('itnews/<int:news_id>/detail', news_detail, name="news_detail"),
    path('services/', services, name="services"),
    path('payment_stages/', payment, name="payment"),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('api/v1/classes-list/', api_classes_list),
]

templates/manager/base_manager.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main-page-manager.css' %}"/>
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    {% endblock %}
</head>
<body>
<header class="main-header">
    <div class="main-header__page-information-change-specialty">
        {% block title %}
        {% endblock %}
    </div>
    <div class="main-header__box">
        <p class="main-header_box-for-notification mb-0">
            <img src="{% static 'images/Group.svg' %}" alt="уведомления" class="main-header__img-notifications"/>
            <span class="main-header__col-notification">
                {% if unreaded_dialogs_counter != 0 %}
                {{ unreaded_dialogs_counter }}
                {% endif %}
            </span>
        </p>
        <a href="{% url 'manager_school:get_manager_profile' %}" class="main__manager-nav-box">
            <p class="main-header__name mb-0">{{request.user.first_name}}</p>
            {% if request.user.img_user %}
            <img src="{{ request.user.img_user.url }}" alt="фото менеждера" class="main-header__img-foto"/>
            {% else %}
            <img src="{% static 'images/no-photo.png' %}" alt="фото менеждера" class="main-header__img-foto"/>
            {% endif %}
        </a>
        <img src="{% static 'images/Polygon.svg' %}" alt="развернуть" class="main-header__open"/>
    </div>
    <div class="main-header__personal-area no-active">
        <div class="main-header__personal-area-options">
            <p class="main-header__personal-area-options-block">
                <a href="{% url 'manager_school:get_manager_profile' %}" class="main-header__personal-area-link">Личный
                    кабинет</a>
                <img src="{% static 'images/Ellipse.svg' %}" alt="point"/>
            </p>
            <img src="{% static 'images/Rectangle.svg' %}" alt="подчеркивание" class="main-header__border-bottom"/>
        </div>

        <div class="main-header__personal-area-options">
            <p class="main-header__personal-area-options-block">
                <a href="{% url 'manager_school:chats' %}" class="main-header__personal-area-link">
                    <span class="main-header__personal-area-col">
                    {% if unreaded_dialogs_counter != 0 %}
                    {{ unreaded_dialogs_counter }}
                    {% endif %}
                    </span> Сообщения</a>
                <img src="{% static 'images/Ellipse.svg' %}" alt="point"/>
            </p>
            <img src="{% static 'images/Rectangle.svg' %}" alt="подчеркивание" class="main-header__border-bottom"/>
        </div>

        <div class="main-header__personal-area-options main-header__personal-area-options_go-out">
            <p class="main-header__personal-area-options-block">
                <a href="{% url 'manager_school:logout' %}" class="main-header__personal-area-link">Выйти</a>
                <img src="{% static 'images/Ellipse.svg' %}" alt="point"/>
            </p>
        </div>
    </div>
</header>

<nav class="main-menu">
    <div class="main-menu__logo">
        <div class="main-header__box-for-logo">
            <a href="{% url 'manager_school:main_page' %}">
                <img src="{% static 'images/logo.svg' %}" alt="logo" class="main-menu__logo-img"/>
            </a>
            <img src="{% static 'images/hide.svg' %}" alt="зыкрыть меню" class="main-menu__hide-img no-active"/>
        </div>
        <div class="main-menu__show">
            <img src="{% static 'images/show.svg' %}" alt="открыть меню" class="main-menu__show-img"/>
        </div>
    </div>

    <div class="main-menu__box-for-item">
        <div class="main-menu__item">
            <a href="{% url 'manager_school:get_groups' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon16.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Группы</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:get_classes' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Расписание</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:get_teachers' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon2.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Преподаватели</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:registration_user' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon2.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Регистрация пользователя</p>
            </a>
        </div>

        <div class="main-menu__item main-menu__item_position">
            <a href="{% url 'manager_school:get_leads' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon18.svg' %}" alt="чат" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Лиды</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:get_contracts' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon16.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Контракты</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:planning_rooms_page' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Планирование</p>
            </a>
        </div>

        <div class="main-menu__item main-menu__item_position">
            <a href="{% url 'manager_school:chats' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon18.svg' %}" alt="чат" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Чат</p>
                <span class="main-menu__item-col">
                    {% if unreaded_dialogs_counter != 0 %}
                    {{ unreaded_dialogs_counter }}
                    {% endif %}
                </span>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:get_news_list' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon4.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Новости школы</p>
            </a>
        </div>

        <div class="main-menu__item main-menu__item-margin">
            <a href="{% url 'manager_school:change_user_info' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon12.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Изменить личные данные</p>
            </a>
        </div>

        <div class="main-menu__item">
            <a href="{% url 'manager_school:logout' %}" class="main-menu__item-box">
                <img src="{% static 'images/icon11.svg' %}" alt="календарь" class="main-menu__item-img"/>
                <p class="main-menu__item-descriotion no-active">Выйти</p>
            </a>
        </div>
    </div>
</nav>

{% block content %}
<main class="main">
    <div class="main__student-tool">
        <a href="{% url 'manager_school:get_classes' %}" class="main__student-tool-box">
            <div class="main__student-tool-box-img">
                <img src="{% static 'images/calendar.svg' %}" alt="календарь ученика" class="main__student-tool-img"/>
            </div>
            <p class="main__student-tool-text-link main__student-tool-link">
                    Учебный календарь
            </p>
        </a>
        <a href="{% url 'manager_school:get_groups' %}" class="main__student-tool-box">
            <div class="main__student-tool-box-img">
                <img src="{% static 'images/process2.jpg' %}" alt="учебный процесс" class="main__student-tool-img"/>
            </div>
            <p class="main__student-tool-text-link main__student-tool-link">
                    Группы
            </p>
        </a>
        <a href="{% url 'manager_school:get_teachers' %}" class="main__student-tool-box">
            <div class="main__student-tool-box-img">
                <img src="{% static 'images/chat.svg' %}" alt="чат" class="main__student-tool-img"/>
            </div>
            <p class="main__student-tool-text-link main__student-tool-link">
                    Преподаватели
            </p>
        </a>
        <a href="{% url 'manager_school:get_leads' %}" class="main__student-tool-box">
            <div class="main__student-tool-box-img">
                <img src="{% static 'images/leads.jpg' %}" alt="чат" class="main__student-tool-img"/>
            </div>
            <p class="main__student-tool-text-link main__student-tool-link">
                    Лиды
            </p>
        </a>
        <a href="{% url 'manager_school:get_contracts' %}" class="main__student-tool-box">
            <div class="main__student-tool-box-img">
                <img src="{% static 'images/contracts.jpg' %}" style="object-fit: cover;" alt="чат"
                     class="main__student-tool-img"/>
            </div>
            <p class="main__student-tool-text-link main__student-tool-link">
                    Контракты
            </p>
        </a>
    </div>
</main>
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

{% block scripts %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}
</body>
</html>