Main_project_school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import entry_page_view

urlpatterns = [
    path('', entry_page_view, name='entry_page'),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('manager-school/', include('manager_school.urls')),
    path('admin_school/',include('admin_school.urls')),
    path('director-school/', include('director_school.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_school/urls.py
from django.urls import path

from .views import *

app_name = 'manager_school'

urlpatterns = [
    path("logout/", logout_request, name='logout'),
    path("login/", login_user, name="login"),
    path('registration_user/<int:lead_id>/', register_user, name='registration_page'),
    path('registration_user/unique/', register_user_unique, name='registration_user'),
    path('profile/', get_manager_profile, name='get_manager_profile'),
    path('profile/change-user-info/', change_user_info, name='change_user_info'),
    path('', main_page_view, name='main_page'),
    path('groups/', get_groups, name='get_groups'),
    path('group/create/', add_group, name='add_group'),
    path('group/<str:slug>/add-classes', create_group_classes_page, name='create_group_classes'),
    path('group/<str:slug>/detail/', get_group_detail, name='get_group_detail'),
    path('group/<str:slug>/settings/', group_settings, name='group_settings'),
    path('group/<str:slug>/journal/', get_group_journal, name='get_group_journal'),
    path('group/<int:group_id>/student/<int:student_id>/card/', get_student_card, name='get_student_card'),
    path('classes/', get_classes, name='get_classes'),
    path('class/<int:class_id>/detail/', get_class_detail, name='get_class_detail'),
    path('teachers/', get_teachers, name='get_teachers'),
    path('teacher/<int:teacher_id>', get_teacher_card, name='get_teacher_card'),
    path('leads/', get_leads, name='get_leads'),
    path('lead-create/', add_lead, name='add_lead'),
    path('lead/<int:lead_id>/history/', lead_history, name='lead_history'),
    path('lead/<int:lead_id>/add/conversation/', add_req_conversation, name='add_req_conversation'),
    path('lead/<int:lead_id>/confirm/', confirm_lead, name='confirm_lead'),
    path('contracts/', get_contracts, name='get_contracts'),
    path('contracts/create/choice/<int:lead_id>/', get_choice, name='get_choice'),
    path('contracts/create/<int:lead_id>/<int:student_id>/', create_contract_page, name='create_contract_page'),
    path('contract/<int:contract_id>/payment/<int:payment_id>/add-stage/', add_payment_stage, name='add_payment_stage'),
    path('contract/<int:contract_id>/', get_contract_detail, name='get_contract_detail'),
    path('payment-stage/<int:payment_stage_id>/', confirm_payment_stage, name='confirm_payment_stage'),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/create-group-chat/<str:slug>/', start_group_chat, name='create_group_chat'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('planning/', get_planning_rooms_page, name='planning_rooms_page'),
    path('planning/class/<int:class_id>/update/', update_class_date_and_time, name='update_class_date_and_time'),
    path('news/', get_news_list, name='get_news_list'),
    path('api/v1/classes-list/', api_classes_list),
    path('api/v1/leads-list/', api_leads_list),
    path('api/v1/news/', news_list),
    path('api/v1/online-courses-list/', api_online_course_list),
    path('api/v1/offline-courses-list/', api_offline_course_list),
    path('api/v1/course-detail/<int:course_id>', api_course_detail),

]

student/urls.py
from django.urls import path
from .views import *


app_name = 'student'

urlpatterns = [
    path("logout/",logout_request,name='logout'),
    path("login/",login_user,name="login"),
    path('change_data/', Change_user_info, name='change_data'),
    path('', main_page_view, name='main_page_view'),
    path('account/', account, name="account"),
    path('calendar/', calendar, name='calendar'),
    path('process/', process, name='process'),
    path('my_group/', group_view, name="group_view"),
    path('group_profile/<int:user_id>/', group_profile, name='group_profile'),
    path('teachers/', teacher_view, name='teacher'),
    path('teacher_profile/<int:teacher_id>/', teacher_profile, name='teacher_profile'),
    path('homework/', homework_view, name="homework"),
    path('exact_hw/<int:homework_id>/', exact_homework, name='exact_hw'),
    path('materials/', materials_view, name="materials_view"),
    path('material_themes/', material_themes, name="material_themes"),
    path('material_detail/<int:class_id>/', material_detail, name="material_detail"),
    path('study_liter/', liter_view, name='study_literature'),
    path('video_materials/', video_materials, name="video_materials"),
    path('video_themes/', video_themes, name='video_themes'),
    path('video_detail/<int:class_id>/', video_detail, name='video_detail'),
    path('class/<int:class_id>/detail/', class_view, name="class_view"),
    path('contact_admin/', contact_admin, name="contact_admin"),
    path('itnews/', itnews, name="itnews"),
    path('itnews/<int:news_id>/detail', news_detail, name="news_detail"),
    path('services/', services, name="services"),
    path('payment_stages/', payment, name="payment"),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('api/v1/classes-list/', api_classes_list),
]

teacher/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'teacher'

urlpatterns = [
    path('', index, name='index'),
    path("login/", login_user, name="login"),
    path("logout/", logout_request,name='logout'),
    path('profile_edit/', profile_edit, name="profile_edit"),
    path('profile/', profile, name="profile"),
    path('calendar/', calendar, name='calendar'),
    path('study_proccess/', study_procces, name='study_procces'),
    path('student_<int:student_id>/', student_detail, name='student_detail'),
    path('class/<int:class_id>/detail/', class_detail, name='class_detail'),
    path('group/', group_detail, name="group_detail"),
    path('materials/', materials, name='materials'),
    path('literature/', text_mat, name='text_mat'),
    path('literature/<int:l_id>/', text_detail, name='text_detail'),
    path('video/', video_mat, name='video_mat'),
    path('video/<slug:slug_v>/', video_detail, name='video_detail'),
    path('homework/', homework, name="homework"),
    path('homework_detail/<int:hw_id>/', homework_detail, name="homework_detail"),
    path('materials_on_theme/', materials_on_theme, name="materials_on_theme"),
    path('materials_on_theme/<int:class_id>/', material_detail, name="material_detail"),
    path('video_courses/', video_courses, name="video_courses"),
    path('video_courses/<int:cs_id>/', vd_crs_detail, name="vd_crs_detail"),
    path('teachers/', teachers, name="teachers"),
    path('teachers/<int:t_id>/', teacher_card, name='teacher_card'),
    path('news/', news, name="news"),
    path('news/<int:post_id>/', post_detail, name='post_detail'),
    path('message-for-admin/', message_for_admin, name='message_for_admin'),
    path('password/', MyPasswordChange.as_view(), name='password'),
    path('password_reset/', MyPasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', MyPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('api/v1/classes-list/', api_classes_list),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
]

templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/autorization_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Страница авторизации</title>
</head>
<body>
<h2>Вход</h2>
{% if user.is_authenticated%}
<p>Вы уже вылонили вход</p>
<a href="{% url 'manager_school:main_page' %}">Главная</a>
<li><a href="{%url 'manager_school:logout'%}">выход</a></li>
{%else%}
<form method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{next}}">
      <input type="submit" value="войти">

</form>
{%endif%}
</body>
</html>

templates/autorization_page_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Страница авторизации</title>
</head>
<body>
<h2>Вход</h2>
{% if user.is_authenticated%}
<p>Вы уже вылонили вход</p>
<a href="{% url 'admin_school:main_page_admin' %}">Главная</a>
<li><a href="{%url 'admin_school:logout_admin'%}">выход</a></li>
{%else%}
<form method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{next}}">
      <input type="submit" value="войти">

</form>
{%endif%}
</body>
</html>

templates/autorization_page_teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Страница авторизации</title>
</head>
<body>
<h2>Вход</h2>
{% if user.is_authenticated%}
<p>Вы уже вылонили вход</p>
<a href="{% url 'teacher:main_page_teacher' %}">Главная</a>
<li><a href="{%url 'teacher:logout_teacher'%}">выход</a></li>

{%else%}

<form method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{next}}">
      <input type="submit" value="войти">

</form>
{%endif%}
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Личный кабинет</title>
</head>

<body>

    <div class="col-md-12 row">
        <div class="col-md-3">
            <a href="{% url 'teacher:index' %}"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
        </div>
        <div class="col-md-7">
            {% block title %}

            {% endblock %}
        </div>
        <div class="col-md-2">
            <a href="{% url 'teacher:account'  %}">{{request.user.last_name}} {{request.user.first_name}}</a>
        </div>
    </div>

    <div class="container p-4 row">
    <div class="col-md-4">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'teacher:calendar' %}">Учебный календарь</a>
            </li>
            <li class="nav-item">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Учебный процесс</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'teacher:homework' %}">ДЗ Студентов</a>
                    <a class="dropdown-item" href="{% url 'teacher:group_detail' %}">Мои группы</a>
                    <a class="dropdown-item" href="#">Учебные материалы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Чат</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Связаться с администратором</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Услуги</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Новости школы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'teacher:logout' %}">Выход</a>
            </li>
        </ul>

    </div>
    <div class="col-md-8">
        {% block content %}
        {% endblock %}
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

templates/base_login.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Home</title>
</head>

<body>

    <div class="container">
        <div class="col-md-6 mx-auto">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

templates/courses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Список курсов</h2>
    <table>
        <tr>
            <th>Название</th>
            <th>Цена</th>
            <th>Начало занятий</th>
            <th>Конец занятий</th>
            <th>Количество занятий</th>
            <th>Расписание</th>
            <th>Изображение</th>
        </tr>
        {% for course in courses %}
        <tr>
            <td><a href="#">{{ course.title }}</a></td>
            <td>{{ course.price }}</td>
            <td>{{ course.start_date }}</td>
            <td>{{ course.finish_date }}</td>
            <td>{{ course.amount }}</td>
            <td>{{ course.graphic }}</td>
            <td><img src="#" width="100" height="100" alt="test"></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/index_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manager_website</title>
</head>
<body>
    <h1>Manager_website</h1>
    <ul><li><a href="{% url 'manager_school:autorization_page' %}">вход</a></li>

    <li><a href="{%url 'manager_school:logout'%}">выход</a></li>
       <li><a href="{%url 'manager_school:registration_page'%}">регистрация</a></li>

    </ul>

</body>
</html>

templates/index_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student_website</title>
</head>
<body>
<h1>Student_Website</h1>
<p><a href="{% url 'student:account' %}">Личный кабинет</a></p>
</body>
</html>

templates/logout_teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выход</title>
</head>
<body>
<h2>Выход</h2>
<p>Вы успешно вышли с сайта</p>
<a href="{% url 'teacher:main_page_teacher' %}">Главная</a>

</body>
</html>

templates/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <h1>Manager_website/Main_page</h1>
    <ul><li><a href="{% url 'manager_school:autorization_page' %}">вход</a></li>

    <li><a href="{%url 'manager_school:logout'%}">выход</a></li>
       <li><a href="{%url 'manager_school:registration_page'%}">регистрация</a></li>

    </ul>

</body>
</html>

templates/main_page_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
</head>
<body>
<h1>Admin</h1>
<li><a href="{%url 'admin_school:logout_admin'%}">выход</a></li>
</body>
</html>

templates/main_page_student.html
{% extends "student/base_student.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block content %}
    <p><a href="{% url 'student:calendar' %}">Учебный календарь</a></p>
    <p><a href="{% url 'student:process' %}">Учебный процесс</a></p>
    <p><a href="#">Чат</a></p>
    <p><a href="{% url 'student:teacher' %}">Преподаватель</a></p>
{% endblock %}

templates/main_page_teacher.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
<h1>Teacher_page</h1>
<div class="container">
    <div class="col-md-8 mx-auto">
        {% if messages %}
        <div class="col mt-4 mb-4">
            {% bootstrap_messages %}
        </div>
        {% endif %}
        <form action="." method="post" class="form-group" enctype="multipart/form-data">
            {{ user_form|crispy }}
            {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Изменить">
        </form>
    </div>
</div>
<li><a href="{%url 'teacher:logout_teacher'%}">выход</a></li>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>