Main_project_school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import entry_page_view

urlpatterns = [
    path('', entry_page_view, name='entry_page'),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('manager-school/', include('manager_school.urls')),
    path('admin_school/',include('admin_school.urls')),
    path('director-school/', include('director_school.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_school/urls.py
from django.urls import path

from .views import *

app_name = 'manager_school'

urlpatterns = [
    path("logout/", logout_request, name='logout'),
    path("login/", login_user, name="login"),
    path('registration_user/<int:lead_id>/', register_user, name='registration_page'),
    path('registration_user/unique/', register_user_unique, name='registration_user'),
    path('profile/', get_manager_profile, name='get_manager_profile'),
    path('profile/change-user-info/', change_user_info, name='change_user_info'),
    path('', main_page_view, name='main_page'),
    path('groups/', get_groups, name='get_groups'),
    path('group/create/', add_group, name='add_group'),
    path('group/<str:slug>/add-classes', create_group_classes_page, name='create_group_classes'),
    path('group/<str:slug>/detail/', get_group_detail, name='get_group_detail'),
    path('group/<str:slug>/settings/', group_settings, name='group_settings'),
    path('group/<str:slug>/journal/', get_group_journal, name='get_group_journal'),
    path('group/<int:group_id>/student/<int:student_id>/card/', get_student_card, name='get_student_card'),
    path('classes/', get_classes, name='get_classes'),
    path('class/<int:class_id>/detail/', get_class_detail, name='get_class_detail'),
    path('teachers/', get_teachers, name='get_teachers'),
    path('teacher/<int:teacher_id>', get_teacher_card, name='get_teacher_card'),
    path('leads/', get_leads, name='get_leads'),
    path('lead-create/', add_lead, name='add_lead'),
    path('lead/<int:lead_id>/history/', lead_history, name='lead_history'),
    path('lead/<int:lead_id>/add/conversation/', add_req_conversation, name='add_req_conversation'),
    path('lead/<int:lead_id>/confirm/', confirm_lead, name='confirm_lead'),
    path('contracts/', get_contracts, name='get_contracts'),
    path('contracts/create/choice/<int:lead_id>/', get_choice, name='get_choice'),
    path('contracts/create/<int:lead_id>/<int:student_id>/', create_contract_page, name='create_contract_page'),
    path('contract/<int:contract_id>/payment/<int:payment_id>/add-stage/', add_payment_stage, name='add_payment_stage'),
    path('contract/<int:contract_id>/', get_contract_detail, name='get_contract_detail'),
    path('payment-stage/<int:payment_stage_id>/', confirm_payment_stage, name='confirm_payment_stage'),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/create-group-chat/<str:slug>/', start_group_chat, name='create_group_chat'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('planning/', get_planning_rooms_page, name='planning_rooms_page'),
    path('planning/class/<int:class_id>/update/', update_class_date_and_time, name='update_class_date_and_time'),
    path('news/', get_news_list, name='get_news_list'),
    path('api/v1/classes-list/', api_classes_list),
    path('api/v1/leads-list/', api_leads_list),
    path('api/v1/news/', news_list),
    path('api/v1/online-courses-list/', api_online_course_list),
    path('api/v1/offline-courses-list/', api_offline_course_list),
    path('api/v1/course-detail/<int:course_id>', api_course_detail),

]

student/urls.py
from django.urls import path
from .views import *


app_name = 'student'

urlpatterns = [
    path("logout/",logout_request,name='logout'),
    path("login/",login_user,name="login"),
    path('change_data/', Change_user_info, name='change_data'),
    path('', main_page_view, name='main_page_view'),
    path('account/', account, name="account"),
    path('calendar/', calendar, name='calendar'),
    path('process/', process, name='process'),
    path('my_group/', group_view, name="group_view"),
    path('group_profile/<int:user_id>/', group_profile, name='group_profile'),
    path('teachers/', teacher_view, name='teacher'),
    path('teacher_profile/<int:teacher_id>/', teacher_profile, name='teacher_profile'),
    path('homework/', homework_view, name="homework"),
    path('exact_hw/<int:homework_id>/', exact_homework, name='exact_hw'),
    path('materials/', materials_view, name="materials_view"),
    path('material_themes/', material_themes, name="material_themes"),
    path('material_detail/<int:class_id>/', material_detail, name="material_detail"),
    path('study_liter/', liter_view, name='study_literature'),
    path('video_materials/', video_materials, name="video_materials"),
    path('video_themes/', video_themes, name='video_themes'),
    path('video_detail/<int:class_id>/', video_detail, name='video_detail'),
    path('class/<int:class_id>/detail/', class_view, name="class_view"),
    path('contact_admin/', contact_admin, name="contact_admin"),
    path('itnews/', itnews, name="itnews"),
    path('itnews/<int:news_id>/detail', news_detail, name="news_detail"),
    path('services/', services, name="services"),
    path('payment_stages/', payment, name="payment"),
    path('chats/', get_chats, name='chats'),
    path('chat/create/<int:user_id>/', start_chat_with_user, name='create_dialog'),
    path('chat/<int:chat_id>', get_chat_with_user, name='messages'),
    path('api/v1/classes-list/', api_classes_list),
]

templates/manager/group/create_group.html
{% extends 'manager/base_manager.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block title %}
<p class="main-header__page-information">Создание группы</p>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/main-header-manager.css' %}"/>
<link rel="stylesheet" href="{% static 'css/contract-deal.css' %}"/>
{% endblock %}

{% block content %}
<main>
    <div class="form-wrapper">
        <div class="form-container">
            <h3>Создание группы</h3>
            <form method="post">
                {% csrf_token %}
                <div class="form-content">
                    <div class="input-wrapper">
                        <p>Курс:</p>
                        {{ group_form.course }}
                    </div>
                    <div class="input-wrapper">
                        <p>Куратор:</p>
                        {{ group_form.manager }}
                    </div>
                    <div class="input-wrapper">
                        <p>Преподаватель:</p>
                        {{ group_form.teacher }}
                    </div>
                    <div class="input-wrapper">
                        <p>Название группы:</p>
                        {{ group_form.title }}
                    </div>
                    <input class="submit" style="margin-top: 20px" type="submit" value="Сохранить"/>
                    {{ alert }}
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/manager/group/group-list.html
{% extends 'manager/base_manager.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load tags%}

{% block style %}
<link rel="stylesheet" href="{% static 'css/main-header-manager.css' %}"/>
<link rel="stylesheet" href="{% static 'css/group-list-manager.css' %}"/>
<link rel="stylesheet" href="{% static 'css/students-home-work-manger.css' %}"/>
<link rel="stylesheet" href="{% static 'css/all-groups.css' %}"/>
{% endblock %}

{% block title %}
<p class="main-header__page-information">Группы</p>
<form class="main-header__form-change-course" action="{% url 'manager_school:add_group' %}" method="get">
    <div class="add-group__container">
        <div>
            <button type="submit" class="students-home-work__but-filter">Добавить группу</button>
        </div>
    </div>
</form>
<form method="get" class="main-header__form-change-course">
    <div class="main-header__change-speciality">
        <div class="main-header__box-for-change-speciality">
            <p class="main-header__button-change-speciality m-0">
                {% if selected_course %}
                {{ selected_course.title }}
                {% else %}
                Курс...
                {% endif %}
            </p>
            <div class="main-header__list-speciality no-active">
                <input type="text" name="course" hidden class="main-header__change-course"/>
                <p class="main-header__wrapp-for-speciality-link m-0" data-value="">
                    Все
                </p>
                {% for course in all_courses %}
                <p class="main-header__wrapp-for-speciality-link m-0" data-value="{{ course.id }}">
                    {{ course.title }}
                </p>
                {% endfor %}
            </div>
        </div>
        <div>
            <button class="students-home-work__but-filter">Фильтровать</button>
        </div>
    </div>
</form>
{% endblock %}

{% block content %}
<main>
    <div class="all-groups__container">
        {% for course in courses%}
        <div class="all-groups__course">
            <h2 class="all-groups__course-name">
                {{ course.title }}
            </h2>
            <div class="slider__box slider{% if not forloop.first %}{{forloop.counter0}}{% endif %}">
                <div class="slider__wrapper">
                    {% for group in course.groups.all %}
                    <div class="slider__item">
                        <a class="slider__item-content-box"
                            href="{% url 'manager_school:get_group_detail' slug=group.slug %}">
                            {% if forloop.counter|divisibleby:"2" %}
                            <img height="100" width="100" src="{% static 'images/group_picture.png' %}"
                                 alt="фото группы" style="margin-bottom: 5px">
                            {% else %}
                            <img height="100" width="100" src="{% static 'images/group_picture2.png' %}"
                                 alt="фото группы" style="margin-bottom: 5px">
                            {% endif %}
                            {{ group.title }}
                        </a>
                    </div>
                    {% endfor %}
                </div>

                <img src="{% static 'images/left_arrow.svg' %}" alt="left" class="slider__control slider__control_left"/>
                <img src="{% static 'images/arrow_right.svg' %}" alt="right"
                     class="slider__control slider__control_right slider__control_show"/>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/main-header-manager.js' %}"></script>
<script src="{% static 'js/all-groups.js' %}"></script>
{% endblock %}



templates/manager/group/group_detail.html
{% extends 'manager/base_manager.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/group.css' %}">
    <link rel="stylesheet" href="{% static 'css/main-group.css' %}">
{% endblock %}

{% block title %}
    <p class="main-header__page-information">Группа {{ group.title }}</p>
{% endblock %}

{% block content %}
    <main class="group">
        <div class="group__container">
            <div class="d-flex flex-column">
                <div style="display: flex; justify-content: space-between; width: 69%; flex-wrap: wrap;">
                    <a href="{% url 'manager_school:get_group_journal' slug=group.slug %}"
                       class="group__sent-message-link">
                        <p class="group__box-for-link">Журнал посещаемости</p>
                    </a>
                    <a href="{% url 'manager_school:group_settings' slug=group.slug %}"
                       class="group__sent-message-link">
                        <p class="group__box-for-link">Настройки группы</p>
                    </a>
                    {% if not group_chat %}
                        <a href="{% url 'manager_school:create_group_chat' slug=group.slug %}"
                           class="group__sent-message-link">
                            <p class="group__box-for-link">Создать чат группы</p>
                        </a>
                    {% endif %}
                    {% if not group.classes.all %}
                        <a href="{% url 'manager_school:create_group_classes' slug=group.slug %}"
                           class="group__sent-message-link">
                            <p class="group__box-for-link">Установить расписание</p>
                        </a>
                    {% endif %}
                </div>
                <div class="group__list-students">
                    <p class="group__name-list">Список учеников</p>
                    {% for student in group.students.all %}
                        <div class="group__student-box">
                            <p class="group__box-for-foto-student">
                                {% if student.img_user %}
                                    <img src="{{ student.img_user.url }}" style="object-fit: cover;" alt="фото студента"
                                         class="group__student-foto"/>
                                {% else %}
                                    <img src="{% static 'images/no-photo.png' %}" style="object-fit: cover;"
                                         alt="фото студента"
                                         class="group__student-foto"/>
                                {% endif %}
                                <span class="group__check-online"></span>
                            </p>
                            <p class="group__student-last-name">{{ student.last_name }}</p>
                            <p class="group__student-first-name">{{ student.first_name }}</p>
                            <p class="group__student-patronymic">{{ student.surname }}</p>
                            <a href="{% url 'manager_school:get_student_card' group_id=group.id student_id=student.id %}"
                               class="group__sent-message-link">
                                <p class="group__box-for-link">Профиль</p>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% if group.teacher %}
                {% with teacher=group.teacher %}
                    <div class="group__box-for-teacher">
                        <p class="group__teacher">Преподаватель</p>
                        {% if teacher.img_user %}
                            <img src="{{ teacher.img_user.url }}" style="object-fit: cover;" alt="фото преподавателя"
                                 class="group__teacher-foto"/>
                        {% else %}
                            <img src="{% static 'images/no-photo.png' %}" style="object-fit: cover;"
                                 alt="фото преподавателя"
                                 class="group__teacher-foto"/>
                        {% endif %}
                        <a href="{% url 'manager_school:get_teacher_card' teacher_id=teacher.id %}">
                            <p class="group__first-name-and-patronymic">{{ teacher.first_name }} {{ teacher.surname }}</p>
                            <p class="group__last-name">{{ teacher.last_name }}</p>
                        </a>
                    </div>
                {% endwith %}
            {% endif %}
        </div>
    </main>

{% endblock %}


{% block scripts %}
    <script src="{% static 'js/main-header.js' %}"></script>
{% endblock %}

templates/manager/group/group_journal.html
{% extends 'manager/base_manager.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load tags %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/main-header-manager.css' %}"/>
<link rel="stylesheet" href="{% static 'css/group-list-manager-journal.css' %}"/>
<link rel="stylesheet" href="{% static 'css/students-home-work-manger.css' %}"/>
{% endblock %}

{% block title %}
<p class="main-header__page-information">Группа {{ group.title }}</p>
{% endblock %}

{% block content %}
<main>
    <div class="thead__wrapper-main">
        <table>
            <thead>
            <tr>
                <td class="thead__td-color thead__td-color_light">ФИО</td>
            </tr>
            </thead>
            {% for student in group.students.all %}
            <tr>
                <td class="td__color_dark">{{ student.last_name }} {{ student.first_name }}</td>
            </tr>
            {% endfor %}
        </table>
        <div class="thead__wrapper">
            {% for class in classes %}
            <table>
                <thead>
                <tr>
                    <td class="thead__td-color thead__td-color_light"><a class="link__color-light"
                                                                         href="{% url 'manager_school:get_class_detail' class_id=class.id %}">
                        {{ class.date|date:"d.m.Y" }}</a></td>
                </tr>
                </thead>
                {% for student in group.students.all %}
                <tr>
                    {% get_student_attendance student class as attendance %}
                    {% if attendance %}
                    {% if not attendance.attendance %}
                    <td class="td__color_dark rating" style="background: bisque;">
                        н
                    </td>
                    {% else %}
                    {% if attendance.rating %}
                    <td class="td__color_dark rating" style="background: palegreen;">
                        {{ attendance.rating }}
                    </td>
                    {% endif %}
                    {% endif %}
                    {% else %}
                    <td class="td__color_dark rating" style="background: floralwhite;"></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}


{% block scripts %}
<script src="{% static 'js/main-header-manager.js' %}"></script>
{% endblock %}

templates/manager/group/group_settings.html
{% extends 'manager/base_manager.html' %}
{% load static %}

{% block title %}
    <title>Document</title>
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/main-header.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/group-settings.css' %}"/>
{% endblock %}
<!--  </head>-->
<!--  <body>-->
<!--    <header class="main-header">-->
{% block header %}
    <div class="main-header__page-information-change-specialty">
        <p class="main-header__page-information">Учебный календарь</p>
    </div>
{% endblock %}
{% block content %}
    <main class="change-personal-data">
        <div class="change-personal-data__container">
            <div class="change-personal-data__pod-container">
                <p class="change-personal-data__name">Изменить данные группы</p>
                <div class="change-personal-data__box-for-change">
                    <form method="post">
                        {% csrf_token %}
                        <div class="change-personal-data_box-for-change">
                            <div class="change-personal-data__box-for-user-data change-personal-data__box-for-user-data_width">
                                <p class="change-personal-data__user-data-name">Название</p>
                                <input type="text" class="change-personal-data__change-data" value="{{ group.title }}"
                                       name="title">
                            </div>
                            <div class="change-personal-data__box-for-user-data change-personal-data__box-for-user-data_width">
                                <p class="change-personal-data__user-data-name">Преподаватель</p>
                                <select name="teacher">
                                    <option selected>{{ group.teacher }}</option>
                                    {% for teacher in teachers %}
                                        <option>{{ teacher }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="change-personal-data__box-for-user-data change-personal-data__box-for-user-data_width">
                                <p class="change-personal-data__user-data-name">Менеджер</p>
                                <select name="manager">
                                    <option selected>{{ group.manager }}</option>
                                    {% for manager in managers %}
                                        <option>{{ manager }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="change-personal-data__box-for-user-data change-personal-data__box-for-user-data_width">
                                <p class="change-personal-data__user-data-name">Перенос начала занятий (количество
                                    недель)</p>
                                <input type="number" min="0" class="change-personal-data__change-data" value="--"
                                       name="postponed">
                            </div>
                        </div>
                        <div class="change-personal-data__box-for-save-changes">
                            <button type="submit" class="change-personal-data__but-save">Сохранить</button>
                            <p class="change-personal-data__user-data-name">Удалить группу
                                <input style="margin-left: 10px" type="checkbox" name="delete"></p>
                        </div>
                    {{ alert }}
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/main-header.js' %}"></script>
{% endblock %}

templates/manager/group/planning_rooms_page.html
{% extends 'manager/base_manager.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/main-header-manager.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/group-list-manager-journal.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/students-home-work-manger.css' %}"/>
{% endblock %}

{% block title %}
    <p class="main-header__page-information">Планирование</p>
    <form method="get">
        <div class="main-header__change-speciality" style="">
            <div class="main-header__box-for-change-speciality">
                <select name="year" class="main-header__button-change-speciality" id="year-select"></select>
            </div>
            <div class="main-header__box-for-change-speciality">
                <select name="month" class="main-header__button-change-speciality" id="month-select"></select>
            </div>
            <div class="main-header__box-for-change-speciality">
                <button class="main-header__button-change-speciality">Поиск</button>
            </div>
        </div>
    </form>
    <div class="main-header__list-speciality"></div>
{% endblock %}

{% block content %}
    <main>
        <div class="thead__wrapper-main">
            <table>
                <thead>
                <tr>
                    <td class="thead__td-color thead__td-color_light">Аудитории</td>
                </tr>
                </thead>
                {% for room in rooms %}
                    <tr>
                        <td style="padding: 0px;">
                            <div class="td__color_dark" style="min-height: 150px; padding: 25px;">
                                <div>{{ room.title }}</div>
                                <div style="font-size: 14px;">Мест: {{ room.max_places_count }}</div>
                            </div>
                        </td>
                    </tr>
                    {% for interval in room.time_intervals.all %}
                        {% if forloop.first %}
                        {% else %}
                            <tr>
                                <td style="padding: 0px;">
                                    <div class="td__color_dark" style="min-height: 150px; padding: 25px;"></div>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </table>
            <div class="thead__wrapper">
                {% for date in date_set %}
                    {% check_current_date date as is_current_date %}
                    <table>
                        <thead>
                        <tr>
                            <td class="thead__td-color thead__td-color_light" style="min-width: 160px;">
                                {{ date|date:'D d.m.Y' }}
                            </td>
                        </tr>
                        {% for room in rooms %}
                            {% for interval in room.time_intervals.all %}
                                {% get_room_at_current_day room date interval as classes %}
                                <tr>
                                    <td class="td__color_dark" style="padding: 0px;">
                                        <div class="link__color-light"
                                             style="min-height: 150px;font-size: 14px;color: black!important;
                                                     {% if classes %}background: white;{% endif %}
                                                     {% if is_current_date %}border: 4px solid #0e1935;{% endif %}">
                                            <div style="border-bottom: 1px solid #CED6F2">{{ interval.time_from }} -
                                                {{ interval.time_to }}
                                            </div>
                                            <div>
                                                {% for class in classes %}
                                                    <a href="{% url 'manager_school:get_group_detail' slug=class.groups.slug %}">
                                                        {{ class.groups.title|truncatechars:10 }} {{ class.theme|truncatechars:10 }}
                                                    </a><br>
                                                    Занятие № {{ class.position }}
                                                    <a href="{% url 'manager_school:update_class_date_and_time' class_id=class.id %}">
                                                        Перенести
                                                    </a><br>
                                                    Время: {{ class.start_time }} - {{ class.end_time }}
                                                    Места: {{ class.groups.students.count }} из
                                                    {{ room.max_places_count }}
                                                {% endfor %}
                                            </div>

                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        </thead>
                    </table>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}


{% block scripts %}
    <script>
        var date = new Date();
        var currentMonth = {% if current_month %}{{ current_month }}{% else %}date.getMonth() + 1{% endif %};
        var currentYear = {% if current_month %}{{ current_year }}{% else %}date.getFullYear(){% endif %};

        var months = {
            1: 'Январь',
            2: 'Февраль',
            3: 'Март',
            4: 'Апрель',
            5: 'Май',
            6: 'Июнь',
            7: 'Июль',
            8: 'Август',
            9: 'Сентябрь',
            10: 'Октябрь',
            11: 'Ноябрь',
            12: 'Декабрь',
        };

        const yearSelect = document.getElementById('year-select');
        let yearInner = '';

        for (let i = currentYear + 1; i >= 2000; i--) {
            if (i === currentYear) {
                yearInner += `<option selected>${i}</option>`;
            } else {
                yearInner += `<option>${i}</option>`;
            }
        }
        yearSelect.innerHTML = yearInner;

        const monthSelect = document.getElementById('month-select');
        let monthInner = '';

        for (key in months) {
            if (Number.parseInt(key) === currentMonth) {
                monthInner += `<option selected value="${key}">${months[key]}</option>`;
            } else {
                monthInner += `<option value="${key}">${months[key]}</option>`;
            }
        }
        ;
        monthSelect.innerHTML = monthInner;
    </script>
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}